package app

import (
	"fmt"
	"log/slog"
	"os"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/s3"
	httpapp "github.com/shameoff/more-than-trip/core/internal/app/http"
	"github.com/shameoff/more-than-trip/core/internal/config"
	controllers "github.com/shameoff/more-than-trip/core/internal/http-server/core"
	"github.com/shameoff/more-than-trip/core/internal/lib/converter"
	"github.com/shameoff/more-than-trip/core/internal/lib/logger/sl"
	coreService "github.com/shameoff/more-than-trip/core/internal/services/core"
	"github.com/shameoff/more-than-trip/core/internal/storage/postgres"
	s3Storage "github.com/shameoff/more-than-trip/core/internal/storage/s3"
	httpSwagger "github.com/swaggo/http-swagger"
	_ "github.com/swaggo/http-swagger/example/go-chi/docs" // docs is generated by Swag CLI, you have to import it.
)

type App struct {
	HTTPServer *httpapp.HttpApp
}

func New(log *slog.Logger,
	config *config.Config) *App {
	const op = "app.New"

	log = log.With(
		slog.String("op", op),
	)

	// Init Database connection
	pgDSN, err := converter.ConvertDatabaseConfigToDSN(config.Database)
	if err != nil {
		panic(err)
	}

	storage, err := postgres.New(pgDSN)
	if err != nil {
		log.Error("failed to connect to database", sl.Err(err))
		panic(err)
	}
	log.Debug("successfully connected to database")

	// Init S3 connection
	sess, err := session.NewSession(&aws.Config{
		Region:           aws.String("us-east-1"),
		Endpoint:         aws.String(config.S3.EndpointUrl),
		S3ForcePathStyle: aws.Bool(true),
	})
	if err != nil {
		log.Error("failed to create S3 session", sl.Err(err))
		panic(err)
	}
	s3Client := s3.New(sess)
	s3PhotoService := s3Storage.NewS3Storage(config.S3.PhotosBucket, s3Client)

	// Init core service (Business Logic Layer)
	coreService := coreService.NewCoreService("TOBECONTINUED", log, storage, s3PhotoService)
	coreHandler := controllers.NewCoreHandler(coreService, log)

	// Создание HTTP обработчика
	httpServer := httpapp.New(log, config.HTTP.Port)
	controllers.RegisterRoutes(httpServer.Router, coreHandler)

	// // Init swagger
	httpServer.Router.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("http://localhost:50151/swagger/doc.json"), //The url pointing to API definition
	))

	accessKey := os.Getenv("AWS_ACCESS_KEY_ID")
	secretKey := os.Getenv("AWS_SECRET_ACCESS_KEY")
	fmt.Println("AWS_ACCESS_KEY_ID:", accessKey)
	fmt.Println("AWS_SECRET_ACCESS_KEY:", secretKey)

	return &App{
		HTTPServer: httpServer,
	}
}
