services:
  postgres:
    image: postgres:15
    volumes:
      - "/opt/more-than-trip/postgres_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    ports:
      - "45432:5432"
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  minio:
    image: quay.io/minio/minio:RELEASE.2024-09-09T16-59-28Z
    command: server /data --console-address ":9001"
    volumes:
      - "/opt/more-than-trip/minio_data:/data"
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    ports:
      - "49000:9000"
      - "49001:9001"
    expose:
      - "9000"
      - "9001"
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
