env: "dev" # 'local' to plain logs

http:
  port: 50151
  timeout: 1h

database:
  hostname: "localhost"
  port: 50001
  database: "core"
  user: "postgres"

s3:
  bucket_name: "photos"
  endpoint_url: "https://more-than-trip.shameoff.ru:40443"
  access_key_id: "KSUMOdPwwMOSb42cbmCu"
  photos_bucket: "photos_dev"