name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./core-service
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mtt-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Set up Docker context for remote deployment
        run: |
          docker context create more-than-trip --docker "host=ssh://${{ secrets.SSH_HOST }}:22"

      - name: Use remote Docker context
        run: docker context use more-than-trip

      - name: Deploy application using Docker Compose
        run: |
          docker-compose --context more-than-trip -f docker-compose.prod.yml pull
          docker-compose --context more-than-trip -f docker-compose.prod.yml up -d
